name: Python Package using Conda

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install envirement
      run: pip3 install -r requirements.txt
    - name: Download datasets
      run: ./setup.sh
    - name: Run prediction with pretrained params
      run: |
        python run.py --Final --data_dir inputs --output_dir  outputs/midas/ --depthNet 0
        python run.py --Final --data_dir inputs --output_dir  outputs/leres/ --depthNet 2
    - name: Zip output
      run: zip -r -9 output.zip output/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dictionary_rgb
        release_name: Release output
        draft: false
        prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset
      uses: sekwah41/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./output.zip
        asset_name: output.zip
        asset_content_type: application/zip
